Importing and File Location

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os

#creating Paths
path= r'C:\Users\wjzak\Dropbox\Career Foundry\Data Immersion\Module 4- Python Fundamentals for Data Analysts\07-2025 Instacart Basket Analysis'

#using the path to pull prepared data
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_new.pkl'))

In [3]:
ords_prods_merge.shape

(32404859, 20)

In [4]:
ords_prods_merge['order_hour_of_day'].value_counts(dropna=False)

order_hour_of_day
10.0    2761760
11.0    2736140
14.0    2689136
15.0    2662144
13.0    2660954
12.0    2618532
16.0    2535202
9.0     2454203
17.0    2087654
8.0     1718118
18.0    1636502
19.0    1258305
20.0     976156
7.0      891054
21.0     795637
22.0     634225
23.0     402316
6.0      290493
0.0      218769
1.0      115700
5.0       87961
2.0       69375
4.0       53242
3.0       51281
Name: count, dtype: int64

In [3]:
ords_prods_merge = ords_prods_merge.drop(columns=['Unnamed: 0', 'count'])

Grouping Exercise

In [4]:
#creates subset with 1 million entries from other dataframe
df = ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 18)

In [6]:
df.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_label,busiest_day,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,3139998.0,138.0,prior,28.0,6.0,11.0,3.0,5.0,0.0,both,Mid-range product,Regularly Busy,Most orders
1,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1977647.0,138.0,prior,30.0,6.0,17.0,20.0,1.0,1.0,both,Mid-range product,Regularly Busy,Most orders
2,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,389851.0,709.0,prior,2.0,0.0,21.0,6.0,20.0,0.0,both,Mid-range product,Busiest Days,Average orders
3,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,652770.0,764.0,prior,1.0,3.0,13.0,NaN,10.0,0.0,both,Mid-range product,Slowest Days,Most orders
4,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1813452.0,764.0,prior,3.0,4.0,17.0,9.0,11.0,1.0,both,Mid-range product,Slowest Days,Most orders

In [7]:
#groupby() command- splits product name column
df.groupby('product_name')

In [8]:
#split by department_id and obtain mean for values of order_number column
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              15.577493
2.0              17.320781
3.0              16.084944
4.0              17.530458
5.0              14.763075
6.0              16.658449
7.0              17.031590
8.0              15.076662
9.0              15.447580
10.0             18.681852
11.0             15.447411
12.0             14.327957
13.0             16.548642
14.0             16.960241
15.0             16.121948
16.0             17.803851
17.0             15.593633
18.0             19.674252
19.0             16.899756
20.0             16.255442
21.0             25.535479

In [9]:
#aggregating data without the agg function
df.groupby('department_id')['order_number'].mean()

department_id
1.0     15.577493
2.0     17.320781
3.0     16.084944
4.0     17.530458
5.0     14.763075
6.0     16.658449
7.0     17.031590
8.0     15.076662
9.0     15.447580
10.0    18.681852
11.0    15.447411
12.0    14.327957
13.0    16.548642
14.0    16.960241
15.0    16.121948
16.0    17.803851
17.0    15.593633
18.0    19.674252
19.0    16.899756
20.0    16.255442
21.0    25.535479
Name: order_number, dtype: float64

In [10]:
#same as above using dot notation instead of the square brackets
#not as ideal especiall when working with others on a coding project as it doesnt stand out in the same way
df.groupby('department_id').order_number.mean()

department_id
1.0     15.577493
2.0     17.320781
3.0     16.084944
4.0     17.530458
5.0     14.763075
6.0     16.658449
7.0     17.031590
8.0     15.076662
9.0     15.447580
10.0    18.681852
11.0    15.447411
12.0    14.327957
13.0    16.548642
14.0    16.960241
15.0    16.121948
16.0    17.803851
17.0    15.593633
18.0    19.674252
19.0    16.899756
20.0    16.255442
21.0    25.535479
Name: order_number, dtype: float64

In [11]:
#multiple aggregations to make summary stats
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean  min   max
department_id
1.0              15.577493  1.0  99.0
2.0              17.320781  1.0  96.0
3.0              16.084944  1.0  99.0
4.0              17.530458  1.0  99.0
5.0              14.763075  1.0  99.0
6.0              16.658449  1.0  99.0
7.0              17.031590  1.0  99.0
8.0              15.076662  1.0  98.0
9.0              15.447580  1.0  99.0
10.0             18.681852  1.0  99.0
11.0             15.447411  1.0  99.0
12.0             14.327957  1.0  99.0
13.0             16.548642  1.0  99.0
14.0             16.960241  1.0  99.0
15.0             16.121948  1.0  99.0
16.0             17.803851  1.0  99.0
17.0             15.593633  1.0  99.0
18.0             19.674252  1.0  99.0
19.0             16.899756  1.0  99.0
20.0             16.255442  1.0  99.0
21.0             25.535479  1.0  98.0

In [12]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [13]:
ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_label,busiest_day,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,3139998.0,138.0,prior,28.0,6.0,11.0,3.0,5.0,0.0,both,Mid-range product,Regularly Busy,Most orders,32.0
1,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1977647.0,138.0,prior,30.0,6.0,17.0,20.0,1.0,1.0,both,Mid-range product,Regularly Busy,Most orders,32.0
2,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,389851.0,709.0,prior,2.0,0.0,21.0,6.0,20.0,0.0,both,Mid-range product,Busiest Days,Average orders,5.0
3,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,652770.0,764.0,prior,1.0,3.0,13.0,NaN,10.0,0.0,both,Mid-range product,Slowest Days,Most orders,3.0
4,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1813452.0,764.0,prior,3.0,4.0,17.0,9.0,11.0,1.0,both,Mid-range product,Slowest Days,Most orders,3.0
5,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1701441.0,777.0,prior,16.0,1.0,7.0,26.0,7.0,0.0,both,Mid-range product,Busiest Days,Average orders,26.0
6,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1871483.0,825.0,prior,3.0,2.0,14.0,30.0,2.0,0.0,both,Mid-range product,Regularly Busy,Most orders,9.0
7,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1290456.0,910.0,prior,12.0,3.0,10.0,30.0,1.0,0.0,both,Mid-range product,Slowest Days,Most orders,12.0
8,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,369558.0,1052.0,prior,10.0,1.0,20.0,19.0,1.0,0.0,both,Mid-range product,Busiest Days,Average orders,20.0
9,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,589712.0,1052.0,prior,15.0,1.0,12.0,15.0,2.0,1.0,both,Mid-range product,Busiest Days,Most orders,20.0
10,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1798115.0,1379.0,prior,1.0,5.0,11.0,NaN,1.0,0.0,both,Mid-range product,Regularly Busy,Most orders,10.0
11,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,497193.0,1480.0,prior,36.0,3.0,13.0,7.0,1.0,0.0,both,Mid-range product,Slowest Days,Most orders,43.0
12,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1727826.0,1480.0,prior,38.0,4.0,13.0,7.0,3.0,1.0,both,Mid-range product,Slowest Days,Most orders,43.0
13,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,2694698.0,1480.0,prior,39.0,2.0,12.0,12.0,4.0,1.0,both,Mid-range product,Regularly Busy,Most orders,43.0
14,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,3171753.0,1494.0,prior,6.0,3.0,10.0,2.0,8.0,0.0,both,Mid-range product,Slowest Days,Most orders,13.0

In [14]:
#expands output to not be broken by a line
#pd.options.display.max_rows = None

In [15]:
#creating loyalty label using max order variable above
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [16]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [17]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [18]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [19]:
#df['column'] to look at the info we just changed and validate it is correct
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0     138.0  Regular customer          28.0
1     138.0  Regular customer          30.0
2     709.0      New customer           2.0
3     764.0      New customer           1.0
4     764.0      New customer           3.0
5     777.0  Regular customer          16.0
6     825.0      New customer           3.0
7     910.0  Regular customer          12.0
8    1052.0  Regular customer          10.0
9    1052.0  Regular customer          15.0
10   1379.0      New customer           1.0
11   1480.0    Loyal customer          36.0
12   1480.0    Loyal customer          38.0
13   1480.0    Loyal customer          39.0
14   1494.0  Regular customer           6.0
15   1494.0  Regular customer           7.0
16   1494.0  Regular customer           9.0
17   1540.0  Regular customer           4.0
18   1540.0  Regular customer           5.0
19   1540.0  Regular customer           6.0
20   1540.0  Regular customer           7.0
21   1540.0  Regular customer           8.0
22   1540.0  Regular customer           9.0
23   1540.0  Regular customer          14.0
24   1540.0  Regular customer          15.0
25   1540.0  Regular customer          18.0
26   1540.0  Regular customer          19.0
27   1540.0  Regular customer          20.0
28   1540.0  Regular customer          21.0
29   1540.0  Regular customer          22.0
30   1540.0  Regular customer          24.0
31   1540.0  Regular customer          25.0
32   1540.0  Regular customer          27.0
33   1540.0  Regular customer          28.0
34   1598.0      New customer           1.0
35   1598.0      New customer           2.0
36   1598.0      New customer           3.0
37   1647.0      New customer           1.0
38   1647.0      New customer           4.0
39   1647.0      New customer           6.0
40   1647.0      New customer           8.0
41   1647.0      New customer           9.0
42   2833.0      New customer           1.0
43   2850.0  Regular customer           7.0
44   2857.0  Regular customer          24.0
45   3010.0  Regular customer           5.0
46   3029.0      New customer           1.0
47   3395.0      New customer           4.0
48   3904.0      New customer           1.0
49   4006.0    Loyal customer           2.0
50   4006.0    Loyal customer           3.0
51   4006.0    Loyal customer           5.0
52   4006.0    Loyal customer           9.0
53   4006.0    Loyal customer          12.0
54   4122.0  Regular customer          11.0
55   4141.0      New customer           2.0
56   4343.0      New customer           1.0
57   4553.0      New customer           3.0
58   4845.0  Regular customer           6.0
59   6866.0      New customer           1.0

TASK 4.8 Start---

In [20]:
#aggregating data without the agg function
df.groupby('department_id')['order_number'].mean()

department_id
1.0     15.577493
2.0     17.320781
3.0     16.084944
4.0     17.530458
5.0     14.763075
6.0     16.658449
7.0     17.031590
8.0     15.076662
9.0     15.447580
10.0    18.681852
11.0    15.447411
12.0    14.327957
13.0    16.548642
14.0    16.960241
15.0    16.121948
16.0    17.803851
17.0    15.593633
18.0    19.674252
19.0    16.899756
20.0    16.255442
21.0    25.535479
Name: order_number, dtype: float64

In [21]:
#multiple aggregations to make summary stats
ords_prods_merge.agg({'order_number': ['mean', 'min', 'max']})

      order_number
mean     17.142305
min       1.000000
max      99.000000

3) The average order number is 17 which is about what most of the department items are at in the breakdown above.

In [22]:
#my loyalty flag code is above
#summary statistics for each of them
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

5) The loyal customers on average actually end up spending less on items than the new or regular customers.

In [27]:
#create new column for avergae prices by user
ords_prods_merge['avg_prices'] = ords_prods_merge.groupby(['user_id'])['prices'].transform('mean')

In [28]:
ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,...,days_since_prior_order,add_to_cart_order,reordered,_merge,price_label,busiest_day,busiest_period_of_day,max_order,loyalty_flag,avg_prices
0,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,3139998.0,138.0,prior,28.0,6.0,...,3.0,5.0,0.0,both,Mid-range product,Regularly Busy,Most orders,32.0,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1977647.0,138.0,prior,30.0,6.0,...,20.0,1.0,1.0,both,Mid-range product,Regularly Busy,Most orders,32.0,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,389851.0,709.0,prior,2.0,0.0,...,6.0,20.0,0.0,both,Mid-range product,Busiest Days,Average orders,5.0,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,652770.0,764.0,prior,1.0,3.0,...,NaN,10.0,0.0,both,Mid-range product,Slowest Days,Most orders,3.0,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1813452.0,764.0,prior,3.0,4.0,...,9.0,11.0,1.0,both,Mid-range product,Slowest Days,Most orders,3.0,New customer,4.972414
5,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1701441.0,777.0,prior,16.0,1.0,...,26.0,7.0,0.0,both,Mid-range product,Busiest Days,Average orders,26.0,Regular customer,6.935398
6,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1871483.0,825.0,prior,3.0,2.0,...,30.0,2.0,0.0,both,Mid-range product,Regularly Busy,Most orders,9.0,New customer,5.957576
7,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1290456.0,910.0,prior,12.0,3.0,...,30.0,1.0,0.0,both,Mid-range product,Slowest Days,Most orders,12.0,Regular customer,6.680000
8,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,369558.0,1052.0,prior,10.0,1.0,...,19.0,1.0,0.0,both,Mid-range product,Busiest Days,Average orders,20.0,Regular customer,7.162500
9,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,589712.0,1052.0,prior,15.0,1.0,...,15.0,2.0,1.0,both,Mid-range product,Busiest Days,Most orders,20.0,Regular customer,7.162500
10,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1798115.0,1379.0,prior,1.0,5.0,...,NaN,1.0,0.0,both,Mid-range product,Regularly Busy,Most orders,10.0,New customer,5.813636
11,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,497193.0,1480.0,prior,36.0,3.0,...,7.0,1.0,0.0,both,Mid-range product,Slowest Days,Most orders,43.0,Loyal customer,5.081633
12,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1727826.0,1480.0,prior,38.0,4.0,...,7.0,3.0,1.0,both,Mid-range product,Slowest Days,Most orders,43.0,Loyal customer,5.081633
13,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,2694698.0,1480.0,prior,39.0,2.0,...,12.0,4.0,1.0,both,Mid-range product,Regularly Busy,Most orders,43.0,Loyal customer,5.081633
14,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,3171753.0,1494.0,prior,6.0,3.0,...,2.0,8.0,0.0,both,Mid-range product,Slowest Days,Most orders,13.0,Regular customer,6.803797

In [38]:
#creating spender flag to determine types of spenders
ords_prods_merge.loc[ords_prods_merge['avg_prices'] < 10, 'spender_flag'] = 'Low spender'

In [39]:
ords_prods_merge.loc[ords_prods_merge['avg_prices'] >= 10, 'spender_flag'] = 'High spender'

In [44]:
#validating change made above
ords_prods_merge[['user_id', 'spender_flag', 'avg_prices']].tail(60)

           user_id  spender_flag  avg_prices
32404799   85108.0   Low spender    8.306849
32404800   85942.0   Low spender    7.550000
32404801   87400.0   Low spender    7.759459
32404802   90220.0   Low spender    8.007588
32404803   96470.0   Low spender    7.589600
32404804  100859.0   Low spender    9.087755
32404805  102119.0   Low spender    7.251662
32404806  104922.0   Low spender    6.976250
32404807  107690.0   Low spender    7.778632
32404808  109403.0   Low spender    7.006757
32404809  111542.0   Low spender    7.615238
32404810  114963.0  High spender  397.793370
32404811  118871.0   Low spender    7.241190
32404812  121646.0  High spender   10.022764
32404813  124944.0   Low spender    8.400000
32404814  128148.0   Low spender    7.705316
32404815  128148.0   Low spender    7.705316
32404816  128930.0   Low spender    7.524390
32404817  128930.0   Low spender    7.524390
32404818  129901.0   Low spender    8.694872
32404819  142639.0   Low spender    9.872881
32404820  144914.0   Low spender    8.062232
32404821  145111.0   Low spender    8.177328
32404822  145526.0  High spender   76.089009
32404823  145732.0   Low spender    7.681667
32404824  146323.0   Low spender    8.740690
32404825  151977.0   Low spender    8.110390
32404826  153612.0   Low spender    9.400000
32404827  157883.0   Low spender    7.450000
32404828  159099.0   Low spender    7.663559
32404829  159487.0   Low spender    9.092424
32404830  159487.0   Low spender    9.092424
32404831  159487.0   Low spender    9.092424
32404832  159487.0   Low spender    9.092424
32404833  159638.0   Low spender    7.869811
32404834  163632.0   Low spender    8.890000
32404835  163632.0   Low spender    8.890000
32404836  164453.0   Low spender    7.287013
32404837  166038.0   Low spender    7.612409
32404838  166038.0   Low spender    7.612409
32404839  166213.0   Low spender    7.473913
32404840  171743.0   Low spender    6.991949
32404841  172262.0   Low spender    8.036585
32404842  176942.0   Low spender    7.831250
32404843  178693.0   Low spender    8.360085
32404844  178752.0   Low spender    8.643223
32404845  178752.0   Low spender    8.643223
32404846  182948.0   Low spender    7.306667
32404847  182948.0   Low spender    7.306667
32404848  183548.0   Low spender    8.340659
32404849  184081.0   Low spender    7.684426
32404850  187523.0   Low spender    7.812676
32404851  188073.0   Low spender    6.058416
32404852  188073.0   Low spender    6.058416
32404853  197371.0   Low spender    8.814508
32404854  200215.0   Low spender    8.220313
32404855  200377.0   Low spender    7.364516
32404856  200873.0   Low spender    8.500344
32404857  200873.0   Low spender    8.500344
32404858  205926.0   Low spender    8.133333

In [47]:
#counts for each spender type
ords_prods_merge['spender_flag'].value_counts(dropna = False)

spender_flag
Low spender     31770614
High spender      634245
Name: count, dtype: int64

In [45]:
#create new column for median day since prior order by user
ords_prods_merge['median_day'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform('median')

In [46]:
ords_prods_merge.head(5)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,...,reordered,_merge,price_label,busiest_day,busiest_period_of_day,max_order,loyalty_flag,avg_prices,spender_flag,median_day
0,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,3139998.0,138.0,prior,28.0,6.0,...,0.0,both,Mid-range product,Regularly Busy,Most orders,32.0,Regular customer,6.935811,Low spender,8.0
1,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1977647.0,138.0,prior,30.0,6.0,...,1.0,both,Mid-range product,Regularly Busy,Most orders,32.0,Regular customer,6.935811,Low spender,8.0
2,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,389851.0,709.0,prior,2.0,0.0,...,0.0,both,Mid-range product,Busiest Days,Average orders,5.0,New customer,7.930208,Low spender,8.0
3,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,652770.0,764.0,prior,1.0,3.0,...,0.0,both,Mid-range product,Slowest Days,Most orders,3.0,New customer,4.972414,Low spender,9.0
4,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1813452.0,764.0,prior,3.0,4.0,...,1.0,both,Mid-range product,Slowest Days,Most orders,3.0,New customer,4.972414,Low spender,9.0
5,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1701441.0,777.0,prior,16.0,1.0,...,0.0,both,Mid-range product,Busiest Days,Average orders,26.0,Regular customer,6.935398,Low spender,11.0
6,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1871483.0,825.0,prior,3.0,2.0,...,0.0,both,Mid-range product,Regularly Busy,Most orders,9.0,New customer,5.957576,Low spender,20.0
7,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1290456.0,910.0,prior,12.0,3.0,...,0.0,both,Mid-range product,Slowest Days,Most orders,12.0,Regular customer,6.680000,Low spender,6.0
8,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,369558.0,1052.0,prior,10.0,1.0,...,0.0,both,Mid-range product,Busiest Days,Average orders,20.0,Regular customer,7.162500,Low spender,10.0
9,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,589712.0,1052.0,prior,15.0,1.0,...,1.0,both,Mid-range product,Busiest Days,Most orders,20.0,Regular customer,7.162500,Low spender,10.0
10,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1798115.0,1379.0,prior,1.0,5.0,...,0.0,both,Mid-range product,Regularly Busy,Most orders,10.0,New customer,5.813636,Low spender,20.0
11,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,497193.0,1480.0,prior,36.0,3.0,...,0.0,both,Mid-range product,Slowest Days,Most orders,43.0,Loyal customer,5.081633,Low spender,7.0
12,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,1727826.0,1480.0,prior,38.0,4.0,...,1.0,both,Mid-range product,Slowest Days,Most orders,43.0,Loyal customer,5.081633,Low spender,7.0
13,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,2694698.0,1480.0,prior,39.0,2.0,...,1.0,both,Mid-range product,Regularly Busy,Most orders,43.0,Loyal customer,5.081633,Low spender,7.0
14,1,Chocolate Sandwich Cookies,61.0,19.0,5.8,3171753.0,1494.0,prior,6.0,3.0,...,0.0,both,Mid-range product,Slowest Days,Most orders,13.0,Regular customer,6.803797,Low spender,7.0

In [50]:
#creating frequency flag to show frequencty of shopping
ords_prods_merge.loc[ords_prods_merge['median_day'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [51]:
ords_prods_merge.loc[(ords_prods_merge['median_day'] <= 20) & (ords_prods_merge['median_day'] > 10), 'frequency_flag'] = 'Regular customer'

In [52]:
ords_prods_merge.loc[ords_prods_merge['median_day'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [54]:
#counts for each customer frequency
ords_prods_merge['frequency_flag'].value_counts(dropna = True)

frequency_flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
Name: count, dtype: int64

In [55]:
# Export data to pkl
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_new2.pkl'))